<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SspSponsors\Controller\SponsorsController' => __DIR__ . '/src/SspSponsors/Controller/SponsorsController.php',
    'SspSponsors\Module'                       => __DIR__ . '/Module.php',
    'SspSponsorsTest\SampleTest'               => __DIR__ . '/tests/SspSponsors/SampleTest.php',
    'SspSponsorsTest\Framework\TestCase'       => __DIR__ . '/tests/SspSponsors/Framework/TestCase.php',
);
