<div class="page-header">
    <h1>Our Sponsors</h1>
</div>
<div id="block-mine">
    <p>SunshinePHP is made possible by the generous contributions of sponsors. The
        conference is organized by developers for developers. So we strive to keep
        the event as easy to attend as possible and make it the best experience
        possible for attendees of all skill and economic levels.  In order to accomplish
        this we heavily rely on the financial support of the awesome folks listed below.</p>
    <p>To become a sponsor please request a sponsor prospectus
        by using our <a href="/contact" title="Contact form">contact form</a>.</p>

    <?php
    $i = 0;
    $maxPerRow = 3;
    $level = false;

    if ($sponsors) {
        foreach ($sponsors as $sponsor):
            // if this is the first loop we need to prime $level and output first level
            if (!$level) {
                $level = $sponsor['level'];
                echo '<br /><h3>' . $sponsor['level'] . '</h3><br />';
            }
            
            // add new block per sponsor level
            if ($sponsor['level'] != $level) {
                echo '<br /><br /><hr /><h3>' . $sponsor['level'] . '</h3><br />';
                $i = 0;
            }

            // add new row
            if ($i == $maxPerRow) {
                echo '<br /><br />';
                $i = 0;
            }
            ?>

            <a href="<?= $sponsor['link']; ?>" title="<?= $sponsor['title']; ?>" target="_blank">
                <img src="/img/sponsor_badges/<?= $sponsor['image']; ?>" alt="<?= $sponsor['title']; ?>" />
            </a>

            <?php
            $level = $sponsor['level'];
            $i++;

        endforeach; ?>

    <?php } ?>

</div>