<div class="page-header">
    <h1>Our Sponsors</h1>
</div>
<div id="block-mine">
    <p>SunshinePHP is made possible by the generous contributions
        of sponsors. Without their help we wouldn’t have a
        conference.  This conference is driven by developers for
        developers and their companies.  We always strive to keep
        the entrance fee as low as possible and make the best
        experience possible for our visitors.  In order to accomplish
        that we heavily rely on the financial support of our
        awesome sponsors.</p>
    <p>&nbsp;</p>

    <?php
    $i = 1;
    $level = '';

    if ($sponsors) {

        foreach ($sponsors as $sponsor):

            if ($level != $sponsor['level']) {
                echo '<br /><br />';

                $i = 0;
            }

            if ($i == 3) {

                echo '<br /><br />';

                $i = 0;
            }
            ?>

            <a href="<?= $sponsor['link']; ?>" title="<?= $sponsor['title']; ?>" target="_blank">
                <img src="/img/sponsor_badges/<?= $sponsor['image']; ?>" alt="<?= $sponsor['title']; ?>" />
            </a>

            <?php
            $level = $sponsor['level'];

            $i++;

        endforeach; ?>

    <?php } ?>

</div>